name: Package Party Service

on:
  pull_request:
    types: [ opened, reopened ]
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ 3.13 ]
    name: Install UV
    runs-on: ${{ matrix.os }}
    permissions: write-all
    timeout-minutes: 5
    steps:
      - name: Git checkout repository
        uses: actions/checkout@v5
      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install python
        run: uv python install
      - name: Install project dependencies
        run: uv sync
      - name: Run Ruff linter
        run: uv run ruff check --fix --output-format=github
      - name: Run Ruff formatter
        run: uv run ruff format
      - name: Run unit tests
        run: uv run -m pytest --cov=src
      - name: Build package
        run: uv build
